enum Constants {
    static let title = "Задачи"
    static let search = "Поиск"
    static let cancel = "Закрыть"
    static let loading = "Загрузка..."
    static let emptyTasks = "Нет задач"
    static let edit = "Редактировать"
    static let share = "Поделиться"
    static let delete = "Удалить"
    static let loadingError = "Ощибка загрузки данных"
    static let loadingFailureMessage = "Не удалось загрузить список задач"
    static let retry = "Повторить"
    static let skip = "Пропустить"
    static let backward = "Назад"
    static let titlePlaceholder = "Название"
    static let taskPlaceholder = "Задача"
    static let save = "Сохранить"
    static let newTask = "Новая задача"
    static let alertTitle = "Изменения не сохранены"
    static let alertMessage = "Введенные данные будут утеряны"
    static let alertDismiss = "Все равно закрыть"
    static let alertCancel = "Отмена"
}
